services:
  - type: web
    name: eduar-platform-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server-v2 && npm install && npx prisma generate && npm run build
    startCommand: cd server-v2 && npx prisma db push && npm run seed:prod && node dist/main

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        value: eduar-assets
      - key: R2_PUBLIC_URL_BASE
        value: https://assets.eduar-platform.com

